using System;
using System.IO;
using Unity.Collections;
using UnityEngine;

/// <summary>
/// Versioned binary payload describing a distance far LOD for one avatar: a collapsed
/// humanoid skeleton snapshot, a quantized low-poly skinned mesh, and pre-compressed
/// texture payloads. Generated by the SDK at bundle build time and carried in
/// <see cref="BasisBundleConnector.FarLodBase64"/>, so it is available from a
/// connector-only download without loading the AssetBundle.
///
/// The payload arrives over the network (inside the bee connector), so parsing is
/// defensive: hard caps on every count, and any violation aborts the parse.
///
/// Skeleton convention: bones are humanoid bones only, parented to their nearest humanoid
/// ancestor. Rest local TRS is composed through any non-humanoid intermediate transforms at
/// T-pose, which keeps `restLocalRotation * networkDelta` world-equivalent to the original
/// hierarchy (intermediates are static on remotes). Rest rotations double as the TposeLocal
/// array for RemoteBoneJobSystem registration.
/// </summary>
public class BasisFarLodPayload
{
    public const uint MagicValue = 0x444C4642; // "BFLD" little-endian
    public const ushort CurrentVersion = 1;

    public const int MaxBones = 64;
    public const int MaxVertices = 16384;
    public const int MaxIndexCount = 98304;
    public const int MaxTextureDimension = 2048;
    public const int MaxTexturePayloadBytes = 6 * 1024 * 1024;
    public const int MaxTextures = 4;
    public const int MaxPayloadBytes = 16 * 1024 * 1024;

    public enum FarLodTextureFormat : byte
    {
        BC1 = 0,
        ASTC6x6 = 1,
        RGBA32 = 2,
    }

    [Serializable]
    public struct FarLodTexture
    {
        public FarLodTextureFormat Format;
        public ushort Width;
        public ushort Height;
        public byte MipCount;
        public byte[] Data;
    }

    // Skeleton (collapsed humanoid). Parallel arrays, index = bone index.
    public byte[] BoneHumanBodyBone;
    public byte[] BoneParentIndex; // 0xFF = root bone (hips)
    public Vector3[] BoneRestLocalPosition;
    public Quaternion[] BoneRestLocalRotation;

    // Registration anchors, mirroring what BasisRemoteAvatarDriver passes to AddRemotePlayer.
    public Vector2 AvatarEyePosition;
    public Vector2 AvatarMouthPosition;
    public Vector3 AuthoredRootScale = Vector3.one;
    public Vector3 TposeHeadFromRootPosition;
    public Quaternion TposeHeadFromRootRotation = Quaternion.identity;
    public Vector3 TposeHipsFromRootPosition;
    public Quaternion TposeHipsFromRootRotation = Quaternion.identity;

    // Mesh. Positions quantized to 16 bits per axis inside [PositionBoundsMin, PositionBoundsMax]
    // (animator-root space at T-pose). LocalBounds* is the renderer's localBounds in hips space.
    public Vector3 PositionBoundsMin;
    public Vector3 PositionBoundsMax;
    public Vector3 LocalBoundsCenter;
    public Vector3 LocalBoundsExtents;
    public int VertexCount;
    public ushort[] PositionsQ;  // 3 per vertex
    public ushort[] NormalsOct;  // 1 per vertex, 8+8 bit octahedral
    public ushort[] UvQ;         // 2 per vertex
    public byte[] BoneIndexA;    // 1 per vertex
    public byte[] BoneIndexB;    // 1 per vertex
    public byte[] BoneWeightA;   // 1 per vertex; weightB = 255 - weightA
    public ushort[] Indices;
    public FarLodTexture[] Textures = Array.Empty<FarLodTexture>();

    public int BoneCount => BoneHumanBodyBone?.Length ?? 0;
    public int TriangleCount => (Indices?.Length ?? 0) / 3;

    public byte[] Serialize()
    {
        using MemoryStream stream = new MemoryStream(256 * 1024);
        using BinaryWriter writer = new BinaryWriter(stream);

        writer.Write(MagicValue);
        writer.Write(CurrentVersion);
        writer.Write((ushort)0); // flags, reserved

        int boneCount = BoneCount;
        writer.Write((byte)boneCount);
        for (int i = 0; i < boneCount; i++)
        {
            writer.Write(BoneHumanBodyBone[i]);
            writer.Write(BoneParentIndex[i]);
            WriteVector3(writer, BoneRestLocalPosition[i]);
            WriteQuaternion(writer, BoneRestLocalRotation[i]);
        }

        WriteVector2(writer, AvatarEyePosition);
        WriteVector2(writer, AvatarMouthPosition);
        WriteVector3(writer, AuthoredRootScale);
        WriteVector3(writer, TposeHeadFromRootPosition);
        WriteQuaternion(writer, TposeHeadFromRootRotation);
        WriteVector3(writer, TposeHipsFromRootPosition);
        WriteQuaternion(writer, TposeHipsFromRootRotation);

        WriteVector3(writer, PositionBoundsMin);
        WriteVector3(writer, PositionBoundsMax);
        WriteVector3(writer, LocalBoundsCenter);
        WriteVector3(writer, LocalBoundsExtents);

        writer.Write((ushort)VertexCount);
        for (int i = 0; i < VertexCount * 3; i++)
        {
            writer.Write(PositionsQ[i]);
        }
        for (int i = 0; i < VertexCount; i++)
        {
            writer.Write(NormalsOct[i]);
        }
        for (int i = 0; i < VertexCount * 2; i++)
        {
            writer.Write(UvQ[i]);
        }
        writer.Write(BoneIndexA, 0, VertexCount);
        writer.Write(BoneIndexB, 0, VertexCount);
        writer.Write(BoneWeightA, 0, VertexCount);

        writer.Write(Indices.Length);
        for (int i = 0; i < Indices.Length; i++)
        {
            writer.Write(Indices[i]);
        }

        int textureCount = Textures?.Length ?? 0;
        writer.Write((byte)textureCount);
        for (int i = 0; i < textureCount; i++)
        {
            writer.Write((byte)Textures[i].Format);
            writer.Write(Textures[i].Width);
            writer.Write(Textures[i].Height);
            writer.Write(Textures[i].MipCount);
            writer.Write(Textures[i].Data.Length);
            writer.Write(Textures[i].Data, 0, Textures[i].Data.Length);
        }

        writer.Flush();
        return stream.ToArray();
    }

    public string SerializeToBase64()
    {
        return Convert.ToBase64String(Serialize());
    }

    public static BasisFarLodPayload TryParseBase64(string base64)
    {
        if (string.IsNullOrEmpty(base64))
        {
            return null;
        }
        byte[] bytes;
        try
        {
            bytes = Convert.FromBase64String(base64);
        }
        catch (FormatException)
        {
            BasisDebug.LogError("Far LOD payload was not valid base64", BasisDebug.LogTag.Avatar);
            return null;
        }
        return TryParse(bytes);
    }

    public static BasisFarLodPayload TryParse(byte[] bytes)
    {
        if (bytes == null || bytes.Length < 16 || bytes.Length > MaxPayloadBytes)
        {
            return null;
        }
        try
        {
            using MemoryStream stream = new MemoryStream(bytes, false);
            using BinaryReader reader = new BinaryReader(stream);

            if (reader.ReadUInt32() != MagicValue)
            {
                return null;
            }
            ushort version = reader.ReadUInt16();
            if (version == 0 || version > CurrentVersion)
            {
                BasisDebug.LogError($"Far LOD payload version {version} is newer than supported {CurrentVersion}", BasisDebug.LogTag.Avatar);
                return null;
            }
            reader.ReadUInt16(); // flags

            BasisFarLodPayload payload = new BasisFarLodPayload();

            int boneCount = reader.ReadByte();
            if (boneCount == 0 || boneCount > MaxBones)
            {
                return null;
            }
            payload.BoneHumanBodyBone = new byte[boneCount];
            payload.BoneParentIndex = new byte[boneCount];
            payload.BoneRestLocalPosition = new Vector3[boneCount];
            payload.BoneRestLocalRotation = new Quaternion[boneCount];
            for (int i = 0; i < boneCount; i++)
            {
                payload.BoneHumanBodyBone[i] = reader.ReadByte();
                payload.BoneParentIndex[i] = reader.ReadByte();
                payload.BoneRestLocalPosition[i] = ReadVector3(reader);
                payload.BoneRestLocalRotation[i] = ReadQuaternion(reader);
                if (payload.BoneHumanBodyBone[i] >= (byte)HumanBodyBones.LastBone)
                {
                    return null;
                }
                if (payload.BoneParentIndex[i] != 0xFF && payload.BoneParentIndex[i] >= i)
                {
                    // Parents must precede children so the runtime can build in one pass.
                    return null;
                }
            }

            payload.AvatarEyePosition = ReadVector2(reader);
            payload.AvatarMouthPosition = ReadVector2(reader);
            payload.AuthoredRootScale = ReadVector3(reader);
            payload.TposeHeadFromRootPosition = ReadVector3(reader);
            payload.TposeHeadFromRootRotation = ReadQuaternion(reader);
            payload.TposeHipsFromRootPosition = ReadVector3(reader);
            payload.TposeHipsFromRootRotation = ReadQuaternion(reader);

            payload.PositionBoundsMin = ReadVector3(reader);
            payload.PositionBoundsMax = ReadVector3(reader);
            payload.LocalBoundsCenter = ReadVector3(reader);
            payload.LocalBoundsExtents = ReadVector3(reader);

            int vertexCount = reader.ReadUInt16();
            if (vertexCount == 0 || vertexCount > MaxVertices)
            {
                return null;
            }
            payload.VertexCount = vertexCount;
            payload.PositionsQ = ReadUInt16Array(reader, vertexCount * 3);
            payload.NormalsOct = ReadUInt16Array(reader, vertexCount);
            payload.UvQ = ReadUInt16Array(reader, vertexCount * 2);
            payload.BoneIndexA = reader.ReadBytes(vertexCount);
            payload.BoneIndexB = reader.ReadBytes(vertexCount);
            payload.BoneWeightA = reader.ReadBytes(vertexCount);
            if (payload.BoneIndexA.Length != vertexCount || payload.BoneIndexB.Length != vertexCount || payload.BoneWeightA.Length != vertexCount)
            {
                return null;
            }
            for (int i = 0; i < vertexCount; i++)
            {
                if (payload.BoneIndexA[i] >= boneCount || payload.BoneIndexB[i] >= boneCount)
                {
                    return null;
                }
            }

            int indexCount = reader.ReadInt32();
            if (indexCount <= 0 || indexCount > MaxIndexCount || indexCount % 3 != 0)
            {
                return null;
            }
            payload.Indices = ReadUInt16Array(reader, indexCount);
            for (int i = 0; i < indexCount; i++)
            {
                if (payload.Indices[i] >= vertexCount)
                {
                    return null;
                }
            }

            int textureCount = reader.ReadByte();
            if (textureCount > MaxTextures)
            {
                return null;
            }
            payload.Textures = new FarLodTexture[textureCount];
            for (int i = 0; i < textureCount; i++)
            {
                FarLodTexture texture = new FarLodTexture
                {
                    Format = (FarLodTextureFormat)reader.ReadByte(),
                    Width = reader.ReadUInt16(),
                    Height = reader.ReadUInt16(),
                    MipCount = reader.ReadByte(),
                };
                int dataLength = reader.ReadInt32();
                if (texture.Width == 0 || texture.Height == 0 ||
                    texture.Width > MaxTextureDimension || texture.Height > MaxTextureDimension ||
                    dataLength <= 0 || dataLength > MaxTexturePayloadBytes)
                {
                    return null;
                }
                texture.Data = reader.ReadBytes(dataLength);
                if (texture.Data.Length != dataLength)
                {
                    return null;
                }
                payload.Textures[i] = texture;
            }

            return payload;
        }
        catch (Exception e)
        {
            BasisDebug.LogError($"Far LOD payload parse failed: {e.Message}", BasisDebug.LogTag.Avatar);
            return null;
        }
    }

    public int FindBone(HumanBodyBones bone)
    {
        byte value = (byte)bone;
        for (int i = 0; i < BoneCount; i++)
        {
            if (BoneHumanBodyBone[i] == value)
            {
                return i;
            }
        }
        return -1;
    }

    /// <summary>
    /// Rest pose of every bone in animator-root space, composed down the collapsed hierarchy.
    /// Used for bind poses; runtime bone scale is unity (network scale applies at the root).
    /// </summary>
    public void ComputeBoneRootSpace(out Vector3[] positions, out Quaternion[] rotations)
    {
        int boneCount = BoneCount;
        positions = new Vector3[boneCount];
        rotations = new Quaternion[boneCount];
        for (int i = 0; i < boneCount; i++)
        {
            byte parent = BoneParentIndex[i];
            if (parent == 0xFF)
            {
                positions[i] = BoneRestLocalPosition[i];
                rotations[i] = BoneRestLocalRotation[i];
            }
            else
            {
                positions[i] = positions[parent] + rotations[parent] * BoneRestLocalPosition[i];
                rotations[i] = rotations[parent] * BoneRestLocalRotation[i];
            }
        }
    }

    /// <summary>
    /// Builds the skinned far LOD mesh from this payload — the single construction path shared
    /// by the runtime far LOD and the SDK tester. Returns null (with a log) on bad data.
    /// </summary>
    public Mesh CreateMesh()
    {
        try
        {
            int vertexCount = VertexCount;
            Vector3[] vertices = new Vector3[vertexCount];
            Vector3[] normals = new Vector3[vertexCount];
            Vector2[] uv = new Vector2[vertexCount];
            for (int i = 0; i < vertexCount; i++)
            {
                vertices[i] = DequantizePosition(i);
                normals[i] = OctDecodeNormal(NormalsOct[i]);
                uv[i] = DequantizeUv(i);
            }
            int[] triangles = new int[Indices.Length];
            for (int i = 0; i < triangles.Length; i++)
            {
                triangles[i] = Indices[i];
            }

            Mesh mesh = new Mesh { name = "BasisFarLodMesh" };
            mesh.vertices = vertices;
            mesh.normals = normals;
            mesh.uv = uv;
            mesh.triangles = triangles;

            int influenceCount = 0;
            for (int i = 0; i < vertexCount; i++)
            {
                influenceCount += BoneIndexB[i] != BoneIndexA[i] && BoneWeightA[i] < 255 ? 2 : 1;
            }
            using (NativeArray<byte> bonesPerVertex = new NativeArray<byte>(vertexCount, Allocator.Temp))
            using (NativeArray<BoneWeight1> weights = new NativeArray<BoneWeight1>(influenceCount, Allocator.Temp))
            {
                // Struct copies of the using-declared arrays (same buffer) — a using variable
                // is readonly, so its indexer can't be written through directly.
                NativeArray<byte> bonesPerVertexWriter = bonesPerVertex;
                NativeArray<BoneWeight1> weightWriter = weights;
                int cursor = 0;
                for (int i = 0; i < vertexCount; i++)
                {
                    float weightA = BoneWeightA[i] * (1f / 255f);
                    bool twoInfluences = BoneIndexB[i] != BoneIndexA[i] && BoneWeightA[i] < 255;
                    bonesPerVertexWriter[i] = (byte)(twoInfluences ? 2 : 1);
                    if (twoInfluences)
                    {
                        weightWriter[cursor++] = new BoneWeight1 { boneIndex = BoneIndexA[i], weight = weightA };
                        weightWriter[cursor++] = new BoneWeight1 { boneIndex = BoneIndexB[i], weight = 1f - weightA };
                    }
                    else
                    {
                        weightWriter[cursor++] = new BoneWeight1 { boneIndex = BoneIndexA[i], weight = 1f };
                    }
                }
                mesh.SetBoneWeights(bonesPerVertex, weights);
            }

            ComputeBoneRootSpace(out Vector3[] bonePositions, out Quaternion[] boneRotations);
            Matrix4x4[] bindposes = new Matrix4x4[BoneCount];
            for (int i = 0; i < BoneCount; i++)
            {
                bindposes[i] = Matrix4x4.TRS(bonePositions[i], boneRotations[i], Vector3.one).inverse;
            }
            mesh.bindposes = bindposes;
            mesh.bounds = new Bounds(
                (PositionBoundsMin + PositionBoundsMax) * 0.5f,
                PositionBoundsMax - PositionBoundsMin);
            mesh.UploadMeshData(true);
            return mesh;
        }
        catch (Exception e)
        {
            BasisDebug.LogError($"Far LOD mesh rejected: {e.Message}", BasisDebug.LogTag.Avatar);
            return null;
        }
    }

    /// <summary>
    /// Mipmap limit group for decoded far LOD atlases. Script-created textures can't join the
    /// mip STREAMING system (asset-pipeline textures only), but through this group they respect
    /// the global texture quality / mipmap limit — dropping the graphics tier sheds their top
    /// mips like any imported texture.
    /// </summary>
    public const string MipmapLimitGroup = "BasisAvatarFarLod";

    /// <summary>
    /// Builds the atlas texture from the first payload whose compression format this device
    /// supports. Returns null when none apply.
    /// </summary>
    public Texture2D CreateTexture()
    {
        for (int i = 0; i < Textures.Length; i++)
        {
            FarLodTexture texturePayload = Textures[i];
            TextureFormat format;
            switch (texturePayload.Format)
            {
                case FarLodTextureFormat.BC1: format = TextureFormat.DXT1; break;
                case FarLodTextureFormat.ASTC6x6: format = TextureFormat.ASTC_6x6; break;
                case FarLodTextureFormat.RGBA32: format = TextureFormat.RGBA32; break;
                default: continue;
            }
            if (!SystemInfo.SupportsTextureFormat(format))
            {
                continue;
            }
            // Mipmap-limit participation is best-effort: with an active nonzero limit Unity
            // allocates a trimmed chain and full-chain LoadRawTextureData throws. Never let
            // that cost us the texture — fall back to plain construction.
            Texture2D texture = null;
            try
            {
                texture = CreateTextureForPayload(texturePayload, format, useMipmapLimit: true);
            }
            catch (Exception e)
            {
                BasisDebug.Log($"Far LOD atlas mip-limit path unavailable ({e.Message}) — using plain texture.", BasisDebug.LogTag.Avatar);
                texture = null;
            }
            if (texture == null)
            {
                try
                {
                    texture = CreateTextureForPayload(texturePayload, format, useMipmapLimit: false);
                }
                catch (Exception e)
                {
                    BasisDebug.LogError($"Far LOD texture rejected: {e.Message}", BasisDebug.LogTag.Avatar);
                }
            }
            if (texture != null)
            {
                return texture;
            }
        }
        return null;
    }

    private static Texture2D CreateTextureForPayload(in FarLodTexture texturePayload, TextureFormat format, bool useMipmapLimit)
    {
        bool hasMips = texturePayload.MipCount > 1;
        Texture2D texture;
        if (useMipmapLimit && hasMips)
        {
            if (!TextureMipmapLimitGroups.HasGroup(MipmapLimitGroup))
            {
                TextureMipmapLimitGroups.CreateGroup(MipmapLimitGroup);
            }
            texture = new Texture2D(texturePayload.Width, texturePayload.Height, format,
                texturePayload.MipCount, false, false, new MipmapLimitDescriptor(true, MipmapLimitGroup));
        }
        else
        {
            texture = new Texture2D(texturePayload.Width, texturePayload.Height, format, hasMips, false);
        }
        texture.name = "BasisFarLodAtlas";
        texture.wrapMode = TextureWrapMode.Clamp;
        texture.filterMode = FilterMode.Trilinear;
        texture.anisoLevel = 1;
        try
        {
            texture.LoadRawTextureData(texturePayload.Data);
            texture.Apply(false, true);
        }
        catch
        {
            if (Application.isPlaying)
            {
                UnityEngine.Object.Destroy(texture);
            }
            else
            {
                UnityEngine.Object.DestroyImmediate(texture);
            }
            throw;
        }
        return texture;
    }

    public Vector3 DequantizePosition(int vertexIndex)
    {
        Vector3 range = PositionBoundsMax - PositionBoundsMin;
        int baseIndex = vertexIndex * 3;
        return new Vector3(
            PositionBoundsMin.x + range.x * (PositionsQ[baseIndex] * (1f / 65535f)),
            PositionBoundsMin.y + range.y * (PositionsQ[baseIndex + 1] * (1f / 65535f)),
            PositionBoundsMin.z + range.z * (PositionsQ[baseIndex + 2] * (1f / 65535f)));
    }

    public Vector2 DequantizeUv(int vertexIndex)
    {
        return new Vector2(UvQ[vertexIndex * 2] * (1f / 65535f), UvQ[vertexIndex * 2 + 1] * (1f / 65535f));
    }

    public static ushort QuantizeUnorm(float value)
    {
        return (ushort)Mathf.Clamp(Mathf.RoundToInt(Mathf.Clamp01(value) * 65535f), 0, 65535);
    }

    public static ushort OctEncodeNormal(Vector3 normal)
    {
        float sum = Mathf.Abs(normal.x) + Mathf.Abs(normal.y) + Mathf.Abs(normal.z);
        if (sum < 1e-8f)
        {
            normal = Vector3.up;
            sum = 1f;
        }
        float x = normal.x / sum;
        float y = normal.y / sum;
        if (normal.z < 0f)
        {
            float ox = x;
            x = (1f - Mathf.Abs(y)) * (ox >= 0f ? 1f : -1f);
            y = (1f - Mathf.Abs(ox)) * (y >= 0f ? 1f : -1f);
        }
        int ux = Mathf.Clamp(Mathf.RoundToInt((x * 0.5f + 0.5f) * 255f), 0, 255);
        int uy = Mathf.Clamp(Mathf.RoundToInt((y * 0.5f + 0.5f) * 255f), 0, 255);
        return (ushort)(ux | (uy << 8));
    }

    public static Vector3 OctDecodeNormal(ushort encoded)
    {
        float x = ((encoded & 0xFF) * (1f / 255f)) * 2f - 1f;
        float y = (((encoded >> 8) & 0xFF) * (1f / 255f)) * 2f - 1f;
        float z = 1f - Mathf.Abs(x) - Mathf.Abs(y);
        if (z < 0f)
        {
            float ox = x;
            x = (1f - Mathf.Abs(y)) * (ox >= 0f ? 1f : -1f);
            y = (1f - Mathf.Abs(ox)) * (y >= 0f ? 1f : -1f);
        }
        return new Vector3(x, y, z).normalized;
    }

    private static void WriteVector2(BinaryWriter writer, Vector2 value)
    {
        writer.Write(value.x);
        writer.Write(value.y);
    }

    private static void WriteVector3(BinaryWriter writer, Vector3 value)
    {
        writer.Write(value.x);
        writer.Write(value.y);
        writer.Write(value.z);
    }

    private static void WriteQuaternion(BinaryWriter writer, Quaternion value)
    {
        writer.Write(value.x);
        writer.Write(value.y);
        writer.Write(value.z);
        writer.Write(value.w);
    }

    private static Vector2 ReadVector2(BinaryReader reader)
    {
        return new Vector2(reader.ReadSingle(), reader.ReadSingle());
    }

    private static Vector3 ReadVector3(BinaryReader reader)
    {
        return new Vector3(reader.ReadSingle(), reader.ReadSingle(), reader.ReadSingle());
    }

    private static Quaternion ReadQuaternion(BinaryReader reader)
    {
        return new Quaternion(reader.ReadSingle(), reader.ReadSingle(), reader.ReadSingle(), reader.ReadSingle());
    }

    private static ushort[] ReadUInt16Array(BinaryReader reader, int count)
    {
        ushort[] values = new ushort[count];
        for (int i = 0; i < count; i++)
        {
            values[i] = reader.ReadUInt16();
        }
        return values;
    }
}
