"""Bounded RESIDUAL on the polynomial: swivel = poly(t) + Dmax*tanh(MLP(t)). Starts as the (smooth,
port-faithful) poly; the bounded correction cannot make it sharp, so the offline solver number transfers
to Unity (the failure mode of the free MLP). Trained against solver err + temporal pop penalty.
It can only match or beat the poly."""
import argparse
import numpy as np
import torch
import torch.nn as nn
import train_swivel as T
import solver_metric as S
import solver_train as ST
import solver_temporal as STp

DEV = T.DEVICE


def t_elbow_from_swivel(feat, swivel, U, L):
    ax, uu, vv = ST.t_circle_frame(feat)
    pole = uu * torch.cos(swivel).unsqueeze(1) + vv * torch.sin(swivel).unsqueeze(1)
    dist = torch.minimum(feat.norm(dim=1).clamp_min(1e-4), U + L - 1e-4)
    a, rho = ST.t_two_bone(dist, U, L)
    return ST.t_guard(a.unsqueeze(1) * ax + rho.unsqueeze(1) * pole, feat, U + L)


class ResMLP(nn.Module):
    def __init__(self, widths, dmax_deg):
        super().__init__()
        layers, d = [], 3
        for w in widths:
            layers += [nn.Linear(d, w), nn.Tanh()]; d = w
        layers += [nn.Linear(d, 1)]
        self.net = nn.Sequential(*layers)
        self.dmax = dmax_deg * np.pi / 180.0

    def forward(self, x):
        return self.dmax * torch.tanh(self.net(x)).squeeze(1)


def residual_phi(m, feat, polyphi):
    with torch.no_grad():
        d = m(torch.tensor(ST.clamp_feat(feat), dtype=torch.float32, device=DEV)).cpu().numpy()
    return polyphi + d


def train_res(feat, polyphi, E, U, L, cur, prev, trmask, widths, dmax, epochs, seed, wd, pop, gain=1.5):
    keep = trmask[cur] & trmask[prev]
    cur, prev = cur[keep], prev[keep]
    Xc = torch.tensor(ST.clamp_feat(feat[cur]), dtype=torch.float32, device=DEV)
    Xp = torch.tensor(ST.clamp_feat(feat[prev]), dtype=torch.float32, device=DEV)
    Pc = torch.tensor(polyphi[cur], dtype=torch.float32, device=DEV)
    Pp = torch.tensor(polyphi[prev], dtype=torch.float32, device=DEV)
    Ec = torch.tensor(E[cur], dtype=torch.float32, device=DEV)
    Uc, Lc = torch.tensor(U[cur], dtype=torch.float32, device=DEV), torch.tensor(L[cur], dtype=torch.float32, device=DEV)
    Up, Lp = torch.tensor(U[prev], dtype=torch.float32, device=DEV), torch.tensor(L[prev], dtype=torch.float32, device=DEV)
    dhand = (Xc - Xp).norm(dim=1)
    torch.manual_seed(seed)
    m = ResMLP(widths, dmax).to(DEV)
    opt = torch.optim.Adam(m.parameters(), lr=2e-3, weight_decay=wd)
    sched = torch.optim.lr_scheduler.CosineAnnealingLR(opt, epochs)
    n, bs = len(Xc), 8192
    for ep in range(epochs):
        perm = torch.randperm(n, device=DEV)
        for b in range(0, n, bs):
            j = perm[b:b + bs]
            opt.zero_grad()
            ec = t_elbow_from_swivel(Xc[j], Pc[j] + m(Xc[j]), Uc[j], Lc[j])
            ep_ = t_elbow_from_swivel(Xp[j], Pp[j] + m(Xp[j]), Up[j], Lp[j])
            acc = ((ec - Ec[j]).pow(2).sum(1) + 1e-9).sqrt().mean()
            popt = torch.relu((ec - ep_).norm(dim=1) - gain * dhand[j]).pow(2).mean()
            loss = acc + pop * popt
            loss.backward(); opt.step()
        sched.step()
    return m


def emit_residual_csharp(m, dmax_deg, path, poly_err, res_err):
    lins = [l for l in m.net if isinstance(l, nn.Linear)]
    Ws = [l.weight.detach().cpu().numpy() for l in lins]
    Bs = [l.bias.detach().cpu().numpy() for l in lins]
    code, prev = [], ["x", "y", "z"]
    for li, (W, B) in enumerate(zip(Ws, Bs)):
        act = li < len(Ws) - 1
        names = []
        for o in range(W.shape[0]):
            terms = " + ".join(f"{T._fmt(W[o, k])}*{prev[k]}" for k in range(W.shape[1]))
            nm = f"h{li}_{o}" if act else "raw"
            code.append(f"            float {nm} = " + (f"math.tanh({terms} + {T._fmt(B[o])});" if act else f"{terms} + {T._fmt(B[o])};"))
            names.append(nm)
        prev = names
    body = "\n".join(code)
    dmax_rad = dmax_deg * np.pi / 180.0
    txt = f'''using Unity.Burst;
using Unity.Mathematics;

namespace UnityEngine.Animations.Rigging
{{
    /// <summary>
    /// AUTO-GENERATED by tools/neural_ik/solver_residual.py -- DO NOT HAND-EDIT. Re-fit and re-generate.
    ///
    /// A bounded RESIDUAL on BasisArmSwivelModel: swivel = poly(t) + {dmax_deg:.0f}deg * tanh(MLP(t)). The
    /// polynomial does the work; the MLP nudges it by at most {dmax_deg:.0f} degrees. Because the base is the
    /// smooth poly and the correction is bounded, this is smooth ON THE TRAJECTORY (adds no pops) -- the one
    /// regime where the offline solver metric is faithful, so the measured gain TRANSFERS to the live solver
    /// (unlike a free MLP, which finds sharp poles that game the per-frame metric and then flip in Unity).
    ///
    /// This is the ONLY neural pole that beat the tuned polynomial on a metric that tracks the real solver,
    /// and it is a SMALL win: the poly is ~0.8% from the smooth-optimal and this closes most of it.
    /// MEASURED (solver elbow err % of arm, in-sample, VALIDATED numpy port): BasisArmSwivelModel {100*poly_err:.3f}%
    /// -> this {100*res_err:.3f}%. The MLP was trained against the ported solver + a temporal pop penalty.
    /// </summary>
    [BurstCompile]
    public static class BasisArmSwivelNeuralModel
    {{
        public static float SwivelRad(in float3 tipLocal) => SwivelRad(tipLocal, out _);

        public static float SwivelRad(in float3 tipLocal, out float confidence)
        {{
            float poly = BasisArmSwivelModel.SwivelRad(tipLocal, out confidence);
            float len = math.length(tipLocal);
            float3 t = len > 1f ? tipLocal / len : tipLocal;
            float x = t.x, y = t.y, z = t.z;

{body}

            return poly + ({dmax_rad:+.8e}f) * math.tanh(raw);
        }}
    }}
}}
'''
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(txt)


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default="")
    ap.add_argument("--widths", default="32,32"); ap.add_argument("--dmax", type=float, default=15)
    ap.add_argument("--epochs", type=int, default=500); ap.add_argument("--seeds", type=int, default=8)
    ap.add_argument("--wd", type=float, default=1e-4); ap.add_argument("--pop", type=float, default=5.0)
    a = ap.parse_args()
    widths = tuple(int(w) for w in a.widths.split(","))
    feat, phi, rad, clip, E, cur, prev = STp.load_pairs()
    U, L = S.per_clip_UL(feat, E, clip)
    tr, va, _ = T.clip_split(clip, 4)
    polyphi = T.poly_swivel(feat, T.ARM_SIN, T.ARM_COS)   # the FIXED polynomial swivel
    poly_all = S.solver_err(T.benddir_from_phi(feat, polyphi), feat, E, U, L)
    poly_va = S.solver_err(T.benddir_from_phi(feat[va], polyphi[va]), feat[va], E[va], U[va], L[va])
    print(f"device={DEV} pairs={len(cur)}  poly in-sample {100*poly_all:.3f}%  poly held-out {100*poly_va:.3f}%  (dmax={a.dmax} deg)")

    hos, ins_list = [], []
    for s in range(a.seeds):
        m = train_res(feat, polyphi, E, U, L, cur, prev, tr, widths, a.dmax, a.epochs, s, a.wd, a.pop)
        rp = residual_phi(m, feat[va], polyphi[va])
        e = S.solver_err(T.benddir_from_phi(feat[va], rp), feat[va], E[va], U[va], L[va])
        hos.append(e)
        print(f"    seed {s}: held-out {100*e:.3f}%  (poly {100*poly_va:.3f}%)")
    print(f"  held-out: residual mean {100*np.mean(hos):.3f}%  best {100*np.min(hos):.3f}%  vs poly {100*poly_va:.3f}%"
          f"   ({(poly_va-np.mean(hos))/poly_va*100:+.1f}% mean)")

    # IN-SAMPLE (Unity's test, all 20 clips): correction trained on all data. Residual is smooth-by-construction
    # (bounded correction on the smooth poly), so the port is faithful and this transfers to Unity.
    allm = np.ones(len(feat), bool)
    ship = []
    for s in range(4):
        m = train_res(feat, polyphi, E, U, L, cur, prev, allm, widths, a.dmax, a.epochs, s, a.wd, a.pop)
        e = S.solver_err(T.benddir_from_phi(feat, residual_phi(m, feat, polyphi)), feat, E, U, L)
        ship.append((e, m))
    ship.sort(key=lambda x: x[0])
    best_err, best_m = ship[0]

    def traj_pops(swiv):
        el = S.solver_elbow(feat, T.benddir_from_phi(feat, swiv), U, L)
        de = np.linalg.norm(el[cur] - el[prev], axis=1); dh = np.linalg.norm(feat[cur] - feat[prev], axis=1)
        return int(np.sum((de > 0.05) & (dh < 0.01)))
    res_swiv = residual_phi(best_m, feat, polyphi)
    print(f"\n  IN-SAMPLE (Unity NeuralSwivel prediction): residual {100*np.mean([x[0] for x in ship]):.3f}% "
          f"(best {100*best_err:.3f}%) vs poly {100*poly_all:.3f}%  ({(poly_all-best_err)/poly_all*100:+.1f}%)")
    print(f"  trajectory pops (Unity-style): poly {traj_pops(polyphi)}  residual {traj_pops(res_swiv)}  (want <= poly)")
    if a.out:
        emit_residual_csharp(best_m, a.dmax, a.out, poly_all, best_err)
        print(f"  wrote {a.out}")
