using System;
using System.IO;
using UnityEngine;

/// <summary>
/// Versioned binary payload describing a distance imposter for one avatar: a collapsed
/// humanoid skeleton snapshot, a quantized low-poly skinned mesh, and pre-compressed
/// texture payloads. Generated by the SDK at bundle build time and carried in
/// <see cref="BasisBundleConnector.ImposterBase64"/>, so it is available from a
/// connector-only download without loading the AssetBundle.
///
/// The payload arrives over the network (inside the bee connector), so parsing is
/// defensive: hard caps on every count, and any violation aborts the parse.
///
/// Skeleton convention: bones are humanoid bones only, parented to their nearest humanoid
/// ancestor. Rest local TRS is composed through any non-humanoid intermediate transforms at
/// T-pose, which keeps `restLocalRotation * networkDelta` world-equivalent to the original
/// hierarchy (intermediates are static on remotes). Rest rotations double as the TposeLocal
/// array for RemoteBoneJobSystem registration.
/// </summary>
public class BasisImposterPayload
{
    public const uint MagicValue = 0x504D4942; // "BIMP" little-endian
    public const ushort CurrentVersion = 1;

    public const int MaxBones = 64;
    public const int MaxVertices = 16384;
    public const int MaxIndexCount = 98304;
    public const int MaxTextureDimension = 1024;
    public const int MaxTexturePayloadBytes = 4 * 1024 * 1024;
    public const int MaxTextures = 4;
    public const int MaxPayloadBytes = 12 * 1024 * 1024;

    public enum ImposterTextureFormat : byte
    {
        BC1 = 0,
        ASTC6x6 = 1,
        RGBA32 = 2,
    }

    [Serializable]
    public struct ImposterTexture
    {
        public ImposterTextureFormat Format;
        public ushort Width;
        public ushort Height;
        public byte MipCount;
        public byte[] Data;
    }

    // Skeleton (collapsed humanoid). Parallel arrays, index = bone index.
    public byte[] BoneHumanBodyBone;
    public byte[] BoneParentIndex; // 0xFF = root bone (hips)
    public Vector3[] BoneRestLocalPosition;
    public Quaternion[] BoneRestLocalRotation;

    // Registration anchors, mirroring what BasisRemoteAvatarDriver passes to AddRemotePlayer.
    public Vector2 AvatarEyePosition;
    public Vector2 AvatarMouthPosition;
    public Vector3 AuthoredRootScale = Vector3.one;
    public Vector3 TposeHeadFromRootPosition;
    public Quaternion TposeHeadFromRootRotation = Quaternion.identity;
    public Vector3 TposeHipsFromRootPosition;
    public Quaternion TposeHipsFromRootRotation = Quaternion.identity;

    // Mesh. Positions quantized to 16 bits per axis inside [PositionBoundsMin, PositionBoundsMax]
    // (animator-root space at T-pose). LocalBounds* is the renderer's localBounds in hips space.
    public Vector3 PositionBoundsMin;
    public Vector3 PositionBoundsMax;
    public Vector3 LocalBoundsCenter;
    public Vector3 LocalBoundsExtents;
    public int VertexCount;
    public ushort[] PositionsQ;  // 3 per vertex
    public ushort[] NormalsOct;  // 1 per vertex, 8+8 bit octahedral
    public ushort[] UvQ;         // 2 per vertex
    public byte[] BoneIndexA;    // 1 per vertex
    public byte[] BoneIndexB;    // 1 per vertex
    public byte[] BoneWeightA;   // 1 per vertex; weightB = 255 - weightA
    public ushort[] Indices;
    public ImposterTexture[] Textures = Array.Empty<ImposterTexture>();

    public int BoneCount => BoneHumanBodyBone?.Length ?? 0;
    public int TriangleCount => (Indices?.Length ?? 0) / 3;

    public byte[] Serialize()
    {
        using MemoryStream stream = new MemoryStream(256 * 1024);
        using BinaryWriter writer = new BinaryWriter(stream);

        writer.Write(MagicValue);
        writer.Write(CurrentVersion);
        writer.Write((ushort)0); // flags, reserved

        int boneCount = BoneCount;
        writer.Write((byte)boneCount);
        for (int i = 0; i < boneCount; i++)
        {
            writer.Write(BoneHumanBodyBone[i]);
            writer.Write(BoneParentIndex[i]);
            WriteVector3(writer, BoneRestLocalPosition[i]);
            WriteQuaternion(writer, BoneRestLocalRotation[i]);
        }

        WriteVector2(writer, AvatarEyePosition);
        WriteVector2(writer, AvatarMouthPosition);
        WriteVector3(writer, AuthoredRootScale);
        WriteVector3(writer, TposeHeadFromRootPosition);
        WriteQuaternion(writer, TposeHeadFromRootRotation);
        WriteVector3(writer, TposeHipsFromRootPosition);
        WriteQuaternion(writer, TposeHipsFromRootRotation);

        WriteVector3(writer, PositionBoundsMin);
        WriteVector3(writer, PositionBoundsMax);
        WriteVector3(writer, LocalBoundsCenter);
        WriteVector3(writer, LocalBoundsExtents);

        writer.Write((ushort)VertexCount);
        for (int i = 0; i < VertexCount * 3; i++)
        {
            writer.Write(PositionsQ[i]);
        }
        for (int i = 0; i < VertexCount; i++)
        {
            writer.Write(NormalsOct[i]);
        }
        for (int i = 0; i < VertexCount * 2; i++)
        {
            writer.Write(UvQ[i]);
        }
        writer.Write(BoneIndexA, 0, VertexCount);
        writer.Write(BoneIndexB, 0, VertexCount);
        writer.Write(BoneWeightA, 0, VertexCount);

        writer.Write(Indices.Length);
        for (int i = 0; i < Indices.Length; i++)
        {
            writer.Write(Indices[i]);
        }

        int textureCount = Textures?.Length ?? 0;
        writer.Write((byte)textureCount);
        for (int i = 0; i < textureCount; i++)
        {
            writer.Write((byte)Textures[i].Format);
            writer.Write(Textures[i].Width);
            writer.Write(Textures[i].Height);
            writer.Write(Textures[i].MipCount);
            writer.Write(Textures[i].Data.Length);
            writer.Write(Textures[i].Data, 0, Textures[i].Data.Length);
        }

        writer.Flush();
        return stream.ToArray();
    }

    public string SerializeToBase64()
    {
        return Convert.ToBase64String(Serialize());
    }

    public static BasisImposterPayload TryParseBase64(string base64)
    {
        if (string.IsNullOrEmpty(base64))
        {
            return null;
        }
        byte[] bytes;
        try
        {
            bytes = Convert.FromBase64String(base64);
        }
        catch (FormatException)
        {
            BasisDebug.LogError("Imposter payload was not valid base64", BasisDebug.LogTag.Avatar);
            return null;
        }
        return TryParse(bytes);
    }

    public static BasisImposterPayload TryParse(byte[] bytes)
    {
        if (bytes == null || bytes.Length < 16 || bytes.Length > MaxPayloadBytes)
        {
            return null;
        }
        try
        {
            using MemoryStream stream = new MemoryStream(bytes, false);
            using BinaryReader reader = new BinaryReader(stream);

            if (reader.ReadUInt32() != MagicValue)
            {
                return null;
            }
            ushort version = reader.ReadUInt16();
            if (version == 0 || version > CurrentVersion)
            {
                BasisDebug.LogError($"Imposter payload version {version} is newer than supported {CurrentVersion}", BasisDebug.LogTag.Avatar);
                return null;
            }
            reader.ReadUInt16(); // flags

            BasisImposterPayload payload = new BasisImposterPayload();

            int boneCount = reader.ReadByte();
            if (boneCount == 0 || boneCount > MaxBones)
            {
                return null;
            }
            payload.BoneHumanBodyBone = new byte[boneCount];
            payload.BoneParentIndex = new byte[boneCount];
            payload.BoneRestLocalPosition = new Vector3[boneCount];
            payload.BoneRestLocalRotation = new Quaternion[boneCount];
            for (int i = 0; i < boneCount; i++)
            {
                payload.BoneHumanBodyBone[i] = reader.ReadByte();
                payload.BoneParentIndex[i] = reader.ReadByte();
                payload.BoneRestLocalPosition[i] = ReadVector3(reader);
                payload.BoneRestLocalRotation[i] = ReadQuaternion(reader);
                if (payload.BoneHumanBodyBone[i] >= (byte)HumanBodyBones.LastBone)
                {
                    return null;
                }
                if (payload.BoneParentIndex[i] != 0xFF && payload.BoneParentIndex[i] >= i)
                {
                    // Parents must precede children so the runtime can build in one pass.
                    return null;
                }
            }

            payload.AvatarEyePosition = ReadVector2(reader);
            payload.AvatarMouthPosition = ReadVector2(reader);
            payload.AuthoredRootScale = ReadVector3(reader);
            payload.TposeHeadFromRootPosition = ReadVector3(reader);
            payload.TposeHeadFromRootRotation = ReadQuaternion(reader);
            payload.TposeHipsFromRootPosition = ReadVector3(reader);
            payload.TposeHipsFromRootRotation = ReadQuaternion(reader);

            payload.PositionBoundsMin = ReadVector3(reader);
            payload.PositionBoundsMax = ReadVector3(reader);
            payload.LocalBoundsCenter = ReadVector3(reader);
            payload.LocalBoundsExtents = ReadVector3(reader);

            int vertexCount = reader.ReadUInt16();
            if (vertexCount == 0 || vertexCount > MaxVertices)
            {
                return null;
            }
            payload.VertexCount = vertexCount;
            payload.PositionsQ = ReadUInt16Array(reader, vertexCount * 3);
            payload.NormalsOct = ReadUInt16Array(reader, vertexCount);
            payload.UvQ = ReadUInt16Array(reader, vertexCount * 2);
            payload.BoneIndexA = reader.ReadBytes(vertexCount);
            payload.BoneIndexB = reader.ReadBytes(vertexCount);
            payload.BoneWeightA = reader.ReadBytes(vertexCount);
            if (payload.BoneIndexA.Length != vertexCount || payload.BoneIndexB.Length != vertexCount || payload.BoneWeightA.Length != vertexCount)
            {
                return null;
            }
            for (int i = 0; i < vertexCount; i++)
            {
                if (payload.BoneIndexA[i] >= boneCount || payload.BoneIndexB[i] >= boneCount)
                {
                    return null;
                }
            }

            int indexCount = reader.ReadInt32();
            if (indexCount <= 0 || indexCount > MaxIndexCount || indexCount % 3 != 0)
            {
                return null;
            }
            payload.Indices = ReadUInt16Array(reader, indexCount);
            for (int i = 0; i < indexCount; i++)
            {
                if (payload.Indices[i] >= vertexCount)
                {
                    return null;
                }
            }

            int textureCount = reader.ReadByte();
            if (textureCount > MaxTextures)
            {
                return null;
            }
            payload.Textures = new ImposterTexture[textureCount];
            for (int i = 0; i < textureCount; i++)
            {
                ImposterTexture texture = new ImposterTexture
                {
                    Format = (ImposterTextureFormat)reader.ReadByte(),
                    Width = reader.ReadUInt16(),
                    Height = reader.ReadUInt16(),
                    MipCount = reader.ReadByte(),
                };
                int dataLength = reader.ReadInt32();
                if (texture.Width == 0 || texture.Height == 0 ||
                    texture.Width > MaxTextureDimension || texture.Height > MaxTextureDimension ||
                    dataLength <= 0 || dataLength > MaxTexturePayloadBytes)
                {
                    return null;
                }
                texture.Data = reader.ReadBytes(dataLength);
                if (texture.Data.Length != dataLength)
                {
                    return null;
                }
                payload.Textures[i] = texture;
            }

            return payload;
        }
        catch (Exception e)
        {
            BasisDebug.LogError($"Imposter payload parse failed: {e.Message}", BasisDebug.LogTag.Avatar);
            return null;
        }
    }

    public Vector3 DequantizePosition(int vertexIndex)
    {
        Vector3 range = PositionBoundsMax - PositionBoundsMin;
        int baseIndex = vertexIndex * 3;
        return new Vector3(
            PositionBoundsMin.x + range.x * (PositionsQ[baseIndex] * (1f / 65535f)),
            PositionBoundsMin.y + range.y * (PositionsQ[baseIndex + 1] * (1f / 65535f)),
            PositionBoundsMin.z + range.z * (PositionsQ[baseIndex + 2] * (1f / 65535f)));
    }

    public Vector2 DequantizeUv(int vertexIndex)
    {
        return new Vector2(UvQ[vertexIndex * 2] * (1f / 65535f), UvQ[vertexIndex * 2 + 1] * (1f / 65535f));
    }

    public static ushort QuantizeUnorm(float value)
    {
        return (ushort)Mathf.Clamp(Mathf.RoundToInt(Mathf.Clamp01(value) * 65535f), 0, 65535);
    }

    public static ushort OctEncodeNormal(Vector3 normal)
    {
        float sum = Mathf.Abs(normal.x) + Mathf.Abs(normal.y) + Mathf.Abs(normal.z);
        if (sum < 1e-8f)
        {
            normal = Vector3.up;
            sum = 1f;
        }
        float x = normal.x / sum;
        float y = normal.y / sum;
        if (normal.z < 0f)
        {
            float ox = x;
            x = (1f - Mathf.Abs(y)) * (ox >= 0f ? 1f : -1f);
            y = (1f - Mathf.Abs(ox)) * (y >= 0f ? 1f : -1f);
        }
        int ux = Mathf.Clamp(Mathf.RoundToInt((x * 0.5f + 0.5f) * 255f), 0, 255);
        int uy = Mathf.Clamp(Mathf.RoundToInt((y * 0.5f + 0.5f) * 255f), 0, 255);
        return (ushort)(ux | (uy << 8));
    }

    public static Vector3 OctDecodeNormal(ushort encoded)
    {
        float x = ((encoded & 0xFF) * (1f / 255f)) * 2f - 1f;
        float y = (((encoded >> 8) & 0xFF) * (1f / 255f)) * 2f - 1f;
        float z = 1f - Mathf.Abs(x) - Mathf.Abs(y);
        if (z < 0f)
        {
            float ox = x;
            x = (1f - Mathf.Abs(y)) * (ox >= 0f ? 1f : -1f);
            y = (1f - Mathf.Abs(ox)) * (y >= 0f ? 1f : -1f);
        }
        return new Vector3(x, y, z).normalized;
    }

    private static void WriteVector2(BinaryWriter writer, Vector2 value)
    {
        writer.Write(value.x);
        writer.Write(value.y);
    }

    private static void WriteVector3(BinaryWriter writer, Vector3 value)
    {
        writer.Write(value.x);
        writer.Write(value.y);
        writer.Write(value.z);
    }

    private static void WriteQuaternion(BinaryWriter writer, Quaternion value)
    {
        writer.Write(value.x);
        writer.Write(value.y);
        writer.Write(value.z);
        writer.Write(value.w);
    }

    private static Vector2 ReadVector2(BinaryReader reader)
    {
        return new Vector2(reader.ReadSingle(), reader.ReadSingle());
    }

    private static Vector3 ReadVector3(BinaryReader reader)
    {
        return new Vector3(reader.ReadSingle(), reader.ReadSingle(), reader.ReadSingle());
    }

    private static Quaternion ReadQuaternion(BinaryReader reader)
    {
        return new Quaternion(reader.ReadSingle(), reader.ReadSingle(), reader.ReadSingle(), reader.ReadSingle());
    }

    private static ushort[] ReadUInt16Array(BinaryReader reader, int count)
    {
        ushort[] values = new ushort[count];
        for (int i = 0; i < count; i++)
        {
            values[i] = reader.ReadUInt16();
        }
        return values;
    }
}
