using UnityEngine;
using System.Collections.Generic;
using System;
using Basis.Scripts.BasisSdk.Players;
using Basis.Scripts.Networking.NetworkedAvatar;

namespace Cilbox
{
	[CilboxTarget]
	public class CilboxSceneBasis : CilboxBasisCommon
	{
		static readonly HashSet<string> extraWhiteListType = new HashSet<string>(){
			// TUBE world-script additions (Cilbox conversion)
			"Basis.Scripts.BasisSdk.Players.BasisTeleportMode",    // BasisLocalPlayer.Teleport(...) parameter enum
			"Basis.Scripts.Drivers.BasisLocalCameraDriver",        // read-only static CameraInstance (field below)
			"Basis.Scripts.Device_Management.BasisDeviceManagement", // IsCurrentModeVR only (method below)
			"UnityEngine.InputSystem.Keyboard",
			"UnityEngine.InputSystem.Key",
			"UnityEngine.InputSystem.Controls.KeyControl",
			"UnityEngine.InputSystem.Controls.ButtonControl",
			// VRSL DMX GPU readback
			"UnityEngine.Graphics",
			"UnityEngine.Rendering.AsyncGPUReadback",
			"UnityEngine.Rendering.AsyncGPUReadbackRequest",
			"Unity.Collections.NativeArray*",
			// VRSL DMX BasisMediaPlayer bridge (zero-copy OutputTexture -> DMX grid)
			"BasisMediaPlayer",

			// Scene-specific Basis types
			"Basis.Scripts.BasisSdk.Interactions.BasisInteractableButton",
			"Basis.Scripts.BasisSdk.Interactions.BasisInteractableButton+ClickEvent",
			"Basis.BasisImageDownloader",
			"Basis.IBasisImageDownload",
			"Basis.BasisStringDownloader",
			"Basis.IBasisStringDownload",
			"Basis.BasisUrl",
			"BasisNetworkCommon+EventTiming",
			"BasisSDKMirror",
			"BasisSDKMirror+MirrorClearFlags",
			"HVR.Basis.Comms.OSC.OscData",
			"HVR.Basis.Comms.OSC.OscDataKind",
			"HVR.Basis.Comms.OSC.OscMessage",
			"Basis.Shims.*",

			// System IO
			"System.IO.BinaryReader",
			"System.IO.BinaryWriter",
			"System.IO.MemoryStream",
			"System.IO.Stream",
			"System.IO.SeekOrigin",

			// Unity types - core extras
			"UnityEngine.Application*",
			"UnityEngine.CullingGroup",
			"UnityEngine.CustomRenderTexture",
			"UnityEngine.DynamicGI",
			"UnityEngine.QualitySettings",
			"UnityEngine.RuntimePlatform*",
			"UnityEngine.Screen",
			"UnityEngine.SystemInfo",

			// Unity types - math/spatial extras
			"UnityEngine.RaycastHit2D",

			// Unity types - audio extras
			"UnityEngine.AudioReverbZone",
			"UnityEngine.AudioReverbPreset",
			"UnityEngine.AudioListener",
			"UnityEngine.Audio.AudioMixer",
			"UnityEngine.Audio.AudioMixerGroup",
			"UnityEngine.Audio.AudioMixerSnapshot",

			// Unity types - rendering / mesh extras
			"UnityEngine.BillboardRenderer",
			"UnityEngine.LODGroup",
			"UnityEngine.OcclusionArea",
			"UnityEngine.OcclusionPortal",
			"UnityEngine.ReflectionProbe",
			"UnityEngine.Rendering.CameraEvent",
			"UnityEngine.Rendering.LightEvent",
			"UnityEngine.Rendering.LightShadowResolution",
			"UnityEngine.Rendering.ReflectionProbeBlendInfo",
			"UnityEngine.RenderSettings",
			"UnityEngine.Texture3D",
			"UnityEngine.Cubemap",

			// Unity types - lighting
			"UnityEngine.Light",
			"UnityEngine.LightShadowCasterMode",
			"UnityEngine.LightShadows",
			"UnityEngine.LightType",
			"UnityEngine.LightRenderMode",
			"UnityEngine.LightProbeProxyVolume",
			"UnityEngine.LightmapBakeType",
			"UnityEngine.LightProbes",
			"UnityEngine.MixedLightingMode",
			"UnityEngine.ShadowQuality",
			"UnityEngine.ShadowResolution",
			"UnityEngine.ShadowProjection",
			"UnityEngine.ShadowmaskMode",

			// Unity types - camera
			"UnityEngine.Camera",
			"UnityEngine.Camera+CameraCallback",
			"UnityEngine.Camera+GateFitMode",
			"UnityEngine.Camera+MonoOrStereoscopicEye",
			"UnityEngine.Camera+StereoscopicEye",
			"UnityEngine.CameraClearFlags",
			"UnityEngine.CameraType",
			"UnityEngine.DepthTextureMode",
			"UnityEngine.RenderingPath",
			"UnityEngine.StereoTargetEyeMask",
			"UnityEngine.TransparencySortMode",
			"UnityEngine.FogMode",
			"UnityEngine.ColorSpace",

			// Unity types - physics
			"UnityEngine.BoxCollider",
			"UnityEngine.CapsuleCollider",
			"UnityEngine.CharacterController",
			"UnityEngine.Collider",
			"UnityEngine.Collision",
			"UnityEngine.CollisionDetectionMode",
			"UnityEngine.ConfigurableJoint",
			"UnityEngine.ContactPoint",
			"UnityEngine.FixedJoint",
			"UnityEngine.ForceMode",
			"UnityEngine.HingeJoint",
			"UnityEngine.Joint",
			"UnityEngine.JointDrive",
			"UnityEngine.JointLimits",
			"UnityEngine.JointMotor",
			"UnityEngine.JointProjectionMode",
			"UnityEngine.JointSpring",
			"UnityEngine.MeshCollider",
			"UnityEngine.MeshColliderCookingOptions",
			"UnityEngine.PhysicMaterial",
			"UnityEngine.PhysicMaterialCombine",
			"UnityEngine.Physics",
			"UnityEngine.QueryTriggerInteraction",
			"UnityEngine.Rigidbody",
			"UnityEngine.RigidbodyConstraints",
			"UnityEngine.RigidbodyInterpolation",
			"UnityEngine.SphereCollider",
			"UnityEngine.SoftJointLimit",
			"UnityEngine.SoftJointLimitSpring",
			"UnityEngine.SpringJoint",
			"UnityEngine.WheelCollider",
			"UnityEngine.WheelFrictionCurve",
			"UnityEngine.WheelHit",

			// Unity types - particles
			"UnityEngine.ParticleSystem",
			"UnityEngine.ParticleSystem+*",
			"UnityEngine.ParticleSystemRenderer",
			"UnityEngine.ParticleSystemForceField",
			"UnityEngine.ParticleSystemSimulationSpace",
			"UnityEngine.ParticleSystemShapeType",
			"UnityEngine.ParticleSystemSortMode",
			"UnityEngine.ParticleSystemRenderMode",
			"UnityEngine.ParticleSystemStopBehavior",
			"UnityEngine.ParticleSystemEmissionType",

			// Unity AI - NavMesh
			"UnityEngine.AI.NavMesh",
			"UnityEngine.AI.NavMeshAgent",
			"UnityEngine.AI.NavMeshBuildSettings",
			"UnityEngine.AI.NavMeshHit",
			"UnityEngine.AI.NavMeshObstacle",
			"UnityEngine.AI.NavMeshObstacleShape",
			"UnityEngine.AI.NavMeshPath",
			"UnityEngine.AI.NavMeshPathStatus",
			"UnityEngine.AI.NavMeshQueryFilter",
			"UnityEngine.AI.NavMeshTriangulation",
			"UnityEngine.AI.OffMeshLink",
			"UnityEngine.AI.OffMeshLinkData",
			"UnityEngine.AI.ObstacleAvoidanceType",

			// Unity Event Systems extras
			"UnityEngine.EventSystems.PointerEventData+FramePressState",
		};

		static readonly HashSet<string> extraWhiteListFields = new HashSet<string>(){
			// TUBE world-script additions (Cilbox conversion)
			"Basis.Scripts.Drivers.BasisLocalCameraDriver.CameraInstance",

			"UnityEngine.RaycastHit2D.*",

			// Unity physics struct fields
			"UnityEngine.ContactPoint.*",
			"UnityEngine.JointDrive.*",
			"UnityEngine.JointLimits.*",
			"UnityEngine.JointMotor.*",
			"UnityEngine.JointSpring.*",
			"UnityEngine.SoftJointLimit.*",
			"UnityEngine.SoftJointLimitSpring.*",
			"UnityEngine.WheelFrictionCurve.*",
			"UnityEngine.WheelHit.*",

			// Unity AI struct fields
			"UnityEngine.AI.NavMeshHit.*",
			"UnityEngine.AI.OffMeshLinkData.*",
			"UnityEngine.AI.NavMeshTriangulation.*",
		};

		static readonly Dictionary<Type, HashSet<string>> extraMethodWhitelist = new Dictionary<Type, HashSet<string>>()
		{
			// UnityEngine.GameObject: the common whitelist restricts it to SetActive + GetComponent.
			// World scripts routinely read benign members off GameObject references, so allow them here.
			// (AddComponent / SendMessage / BroadcastMessage remain blocked in CheckMethodAllowed.)
			{ typeof(UnityEngine.GameObject), new HashSet<string>{
				"get_transform",
				"get_name",
				"set_name",
				"get_tag",
				"set_tag",
				"CompareTag",
				"get_activeSelf",
				"get_activeInHierarchy",
				"get_layer",
				"set_layer",
				"get_isStatic",
				"get_scene",
				"GetComponentInChildren",
				"GetComponentInParent",
				"GetComponents",
				"GetComponentsInChildren",
				"GetComponentsInParent",
				} },
			// VRSL DMX GPU readback surface (mirrors CilboxPropBasis).
			{ typeof(UnityEngine.Graphics), new HashSet<string>{ "Blit" } },
			{ typeof(UnityEngine.Rendering.AsyncGPUReadback), new HashSet<string>{ "Request" } },
			// BasisMediaPlayer: read-only video output access only. Blocks LoadUrl/LoadLocalPath/
			// LoadSource/Play/Stop/Seek/CaptureScreenshot so sandboxed scenes can't load arbitrary
			// media (bypassing the VideoPlayerShim URL trust prompt) or write screenshots to disk.
			// OutputFrameIsTopLeftOrigin is the per-client orientation flag DMX/video sinks XOR
			// into their flip so the grid isn't upside-down on GPUs that can't normalize it.
			{ typeof(BasisMediaPlayer), new HashSet<string>{
				$"get_{nameof(BasisMediaPlayer.OutputTexture)}",
				$"get_{nameof(BasisMediaPlayer.OutputFrameIsTopLeftOrigin)}",
				} },
			// Restrict BasisDeviceManagement to the single mode query the menu uses.
			{ typeof(Basis.Scripts.Device_Management.BasisDeviceManagement), new HashSet<string>{ "IsCurrentModeVR" } },
			// BasisLocalCameraDriver: only the static CameraInstance field is needed (whitelisted above); block all methods.
			{ typeof(Basis.Scripts.Drivers.BasisLocalCameraDriver), new HashSet<string>() },
			{ typeof(BasisLocalPlayer), new HashSet<string>{
				nameof(BasisLocalPlayer.GetPositionAndRotation),
				nameof(BasisLocalPlayer.Teleport),
				nameof(BasisLocalPlayer.Respawn),
				$"get_{nameof(BasisLocalPlayer.Instance)}",
				} },
			{ typeof(BitConverter), new HashSet<string>{
				"GetBytes", "ToBoolean", "ToChar", "ToDouble", "ToInt16", "ToInt32",
				"ToInt64", "ToSingle", "ToString", "ToUInt16", "ToUInt32", "ToUInt64",
				"DoubleToInt64Bits", "Int64BitsToDouble", "SingleToInt32Bits", "Int32BitsToSingle" } },
			{ typeof(Convert), new HashSet<string>{
				"ToInt16", "ToInt32", "ToInt64", "ToUInt16", "ToUInt32", "ToUInt64",
				"ToByte", "ToSByte", "ToBoolean", "ToChar", "ToSingle", "ToDouble",
				"ToString", "ToBase64String", "FromBase64String",
				"ToDateTime", "ToDecimal" } },
			// UnityEngine.Camera: limit to query/transform helpers + property accessors.
			// Block Render(), CopyFrom(), SetTargetBuffers(), AddCommandBuffer*(),
			// RenderToCubemap(), SetReplacementShader(), SetStereoView/ProjectionMatrix.
			{ typeof(UnityEngine.Camera), new HashSet<string>{
				"CalculateFrustumCorners",
				"CalculateObliqueMatrix",
				"GetStereoNonJitteredProjectionMatrix",
				"GetStereoProjectionMatrix",
				"GetStereoViewMatrix",
				"ResetAspect",
				"ResetCullingMatrix",
				"ResetProjectionMatrix",
				"ResetReplacementShader",
				"ResetTransparencySortSettings",
				"ResetWorldToCameraMatrix",
				"ScreenPointToRay",
				"ScreenToViewportPoint",
				"ScreenToWorldPoint",
				"ViewportPointToRay",
				"ViewportToScreenPoint",
				"ViewportToWorldPoint",
				"WorldToScreenPoint",
				"WorldToViewportPoint",
				"GetAllCameras",
				"get_actualRenderingPath",
				"get_allCameras",
				"get_allCamerasCount",
				"get_allowDynamicResolution",
				"get_allowHDR",
				"get_allowMSAA",
				"get_aspect",
				"get_backgroundColor",
				"get_cameraToWorldMatrix",
				"get_cameraType",
				"get_clearFlags",
				"get_cullingMask",
				"get_current",
				"get_depth",
				"get_depthTextureMode",
				"get_eventMask",
				"get_farClipPlane",
				"get_fieldOfView",
				"get_focalLength",
				"get_forceIntoRenderTexture",
				"get_lensShift",
				"get_main",
				"get_nearClipPlane",
				"get_orthographic",
				"get_orthographicSize",
				"get_pixelHeight",
				"get_pixelRect",
				"get_pixelWidth",
				"get_projectionMatrix",
				"get_rect",
				"get_renderingPath",
				"get_scaledPixelHeight",
				"get_scaledPixelWidth",
				"get_sensorSize",
				"get_stereoActiveEye",
				"get_stereoConvergence",
				"get_stereoEnabled",
				"get_stereoSeparation",
				"get_stereoTargetEye",
				"get_targetDisplay",
				"get_transparencySortAxis",
				"get_transparencySortMode",
				"get_useJitteredProjectionMatrixForTransparentRendering",
				"get_useOcclusionCulling",
				"get_usePhysicalProperties",
				"get_velocity",
				"get_worldToCameraMatrix",
				"set_aspect",
				"set_backgroundColor",
				"set_clearFlags",
				"set_cullingMask",
				"set_depth",
				"set_depthTextureMode",
				"set_eventMask",
				"set_farClipPlane",
				"set_fieldOfView",
				"set_focalLength",
				"set_lensShift",
				"set_nearClipPlane",
				"set_orthographic",
				"set_orthographicSize",
				"set_rect",
				"set_renderingPath",
				"set_sensorSize",
				"set_stereoConvergence",
				"set_stereoSeparation",
				"set_stereoTargetEye",
				"set_targetDisplay",
				"set_transparencySortAxis",
				"set_transparencySortMode",
				"set_useJitteredProjectionMatrixForTransparentRendering",
				"set_useOcclusionCulling",
				"set_usePhysicalProperties",
				} },
			// UnityEngine.Light: getters/setters only, no command buffers. CommandBuffer
			// add/remove can hide arbitrary GPU-side work outside the sandbox surface.
			{ typeof(UnityEngine.Light), new HashSet<string>{
				"get_bakingOutput",
				"get_bounceIntensity",
				"get_color",
				"get_colorTemperature",
				"get_commandBufferCount",
				"get_cookie",
				"get_cookieSize",
				"get_cullingMask",
				"get_intensity",
				"get_lightShadowCasterMode",
				"get_range",
				"get_renderMode",
				"get_shadowBias",
				"get_shadowCustomResolution",
				"get_shadowNearPlane",
				"get_shadowNormalBias",
				"get_shadowResolution",
				"get_shadowStrength",
				"get_shadows",
				"get_spotAngle",
				"get_type",
				"get_useColorTemperature",
				"set_bounceIntensity",
				"set_color",
				"set_colorTemperature",
				"set_cookie",
				"set_cookieSize",
				"set_cullingMask",
				"set_intensity",
				"set_lightShadowCasterMode",
				"set_range",
				"set_renderMode",
				"set_shadowBias",
				"set_shadowCustomResolution",
				"set_shadowNearPlane",
				"set_shadowNormalBias",
				"set_shadowResolution",
				"set_shadowStrength",
				"set_shadows",
				"set_spotAngle",
				"set_type",
				"set_useColorTemperature",
				} },
			// UnityEngine.Physics static raycast/overlap surface.
			{ typeof(UnityEngine.Physics), new HashSet<string>{
				"BoxCast", "BoxCastAll", "BoxCastNonAlloc",
				"CapsuleCast", "CapsuleCastAll", "CapsuleCastNonAlloc",
				"CheckBox", "CheckCapsule", "CheckSphere",
				"ClosestPoint",
				"ComputePenetration",
				"GetIgnoreLayerCollision",
				"IgnoreCollision",
				"IgnoreLayerCollision",
				"Linecast",
				"OverlapBox", "OverlapBoxNonAlloc",
				"OverlapCapsule", "OverlapCapsuleNonAlloc",
				"OverlapSphere", "OverlapSphereNonAlloc",
				"Raycast", "RaycastAll", "RaycastNonAlloc",
				"SphereCast", "SphereCastAll", "SphereCastNonAlloc",
				"get_autoSimulation", "get_autoSyncTransforms", "get_gravity",
				"get_queriesHitBackfaces", "get_queriesHitTriggers",
				"get_sleepThreshold", "get_defaultContactOffset",
				} },
			// UnityEngine.Screen: read-only platform info.
			{ typeof(UnityEngine.Screen), new HashSet<string>{
				"get_currentResolution",
				"get_dpi",
				"get_fullScreen",
				"get_fullScreenMode",
				"get_height",
				"get_orientation",
				"get_resolutions",
				"get_safeArea",
				"get_width",
				} },
			// UnityEngine.SystemInfo: device fingerprinting is the privacy concern.
			// Allow a curated set of harmless capability queries.
			{ typeof(UnityEngine.SystemInfo), new HashSet<string>{
				"get_graphicsDeviceType",
				"get_graphicsMemorySize",
				"get_graphicsShaderLevel",
				"get_processorCount",
				"get_processorFrequency",
				"get_supportsAsyncCompute",
				"get_supportsAudio",
				"get_supportsComputeShaders",
				"get_supportsGyroscope",
				"get_supportsInstancing",
				"get_supportsMotionVectors",
				"get_supportsRawShadowDepthSampling",
				"get_supportsShadows",
				"get_supportsSparseTextures",
				"get_supportsVibration",
				"get_systemMemorySize",
				"IsFormatSupported",
				} },
			// UnityEngine.AI.NavMesh: read-only query surface only. Block AddNavMeshData /
			// RemoveNavMeshData / SetNavMeshLayerCost / RemoveAllNavMeshData — those mutate
			// the global navmesh and would break pathing for every script in scene.
			{ typeof(UnityEngine.AI.NavMesh), new HashSet<string>{
				"CalculatePath",
				"CalculateTriangulation",
				"FindClosestEdge",
				"GetAreaCost",
				"GetAreaFromName",
				"GetSettingsByID",
				"GetSettingsByIndex",
				"GetSettingsCount",
				"GetSettingsNameFromID",
				"Raycast",
				"SamplePosition",
				"get_avoidancePredictionTime",
				"get_pathfindingIterationsPerFrame",
				} },
			// UnityEngine.QualitySettings: keep read-only; deny SetQualityLevel which yanks the entire scene render path.
			{ typeof(UnityEngine.QualitySettings), new HashSet<string>{
				"GetQualityLevel",
				"GetQualitySettings",
				"get_activeColorSpace",
				"get_anisotropicFiltering",
				"get_antiAliasing",
				"get_desiredColorSpace",
				"get_lodBias",
				"get_masterTextureLimit",
				"get_maximumLODLevel",
				"get_names",
				"get_pixelLightCount",
				"get_realtimeReflectionProbes",
				"get_shadowCascade2Split",
				"get_shadowCascade4Split",
				"get_shadowCascades",
				"get_shadowDistance",
				"get_shadowProjection",
				"get_shadowResolution",
				"get_shadows",
				"get_softParticles",
				"get_softVegetation",
				"get_vSyncCount",
				} },
		};

		protected override HashSet<string> ExtraWhiteListType => extraWhiteListType;
		protected override HashSet<string> ExtraWhiteListFields => extraWhiteListFields;
		protected override Dictionary<Type, HashSet<string>> ExtraMethodWhitelist => extraMethodWhitelist;

		static readonly HashSet<string> mergedWhiteListType = MergeTypes(extraWhiteListType);
		public static HashSet<string> GetWhiteListTypes() => mergedWhiteListType;
	}
}
